# Generated by Django 4.2.4 on 2023-08-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("readit_api", "0003_alter_post_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreadit",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
